[project]
name = "multipurpose-chatbot"
version = "0.1.0"
description = ""
authors = [
    {name = "Shishupal Rajpurohit",email = "132904812+ShishupalRajpurohit@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0.0"
dependencies = [
    "pandas (>=2.3.1,<3.0.0)",
    "chainlit (>=2.6.2,<3.0.0)",
    "langchain-openai (>=0.3.28,<0.4.0)",
    "langchain (>=0.3.26,<0.4.0)",
    "flask (>=3.1.1,<4.0.0)",
    "langchain-google-genai (>=2.1.8,<3.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "langchain-groq (>=0.3.6,<0.4.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
